sudo: required
dist: trusty
language: node_js
addons:
  apt:
    sources:
      - google-chrome
env:
  - CXX=g++-4.8
services:
  - redis-server
cache:
  directories:
  - node_modules # NPM packages
before_install:
  - sudo apt-get -qq update
  - npm install
install:
  npm run build
node_js:
  - "5.11"
notifications:
  email:
    recipients:
      - cooluhuru@gmail.com
    on_success: always
    on_failure: always
after_success:
  - npm run coveralls